name: Deploy APP "Test" -> Homolog
on:
  workflow_dispatch:
  push:
    branches: ["master"]

env:
  APP_NAME:  ${{ secrets.APP_NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      id: checkout
      uses: actions/checkout@v2

    - name: Login to GCR
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker Client
      id: configure-docker-client
      run:  |-
        gcloud auth configure-docker --quiet

    - name: Build Docker Image
      id: build-docker-image
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
      run: docker build -t $APP_NAME:latest .

    - name: Push Docker Image to Container Registry GCR
      id: push-docker-image
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        IMAGE_TAG: ${{ github.sha }}
      run: |- 
        docker tag $APP_NAME:latest gcr.io/$PROJECT_ID/services/$APP_NAME/homolog:latest
        docker tag $APP_NAME:latest gcr.io/$PROJECT_ID/services/$APP_NAME/homolog:$IMAGE_TAG
        docker push gcr.io/$PROJECT_ID/services/$APP_NAME/homolog:latest
        docker push gcr.io/$PROJECT_ID/services/$APP_NAME/homolog:$IMAGE_TAG
