name: Deploy APP "Test" -> Homolog
on:
  workflow_dispatch:
  push:
    branches: ["master"]

env:
  DOCKER_TAG: latest
  GCP_REGION: ${{ secrets.AWS_REGION }}}
  GCR_REGISTRY: ${{ secrets.GCR_REGISTRY}}
  APP_NAME:  ${{ secrets.APP_NAME }}
  INSTANCE_TAG:  ${{ secrets.INSTANCE_TAG }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      id: checkout
      uses: actions/checkout@v2

    - name: Login to GCR
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker Client
      id: configure-docker-client
      run:  |-
        gcloud auth configure-docker --quiet

    - name: Build Docker Image
      id: build-docker-image
      env:
        GCR_REGISTRY: ${{ secrets.GCR_REGISTRY}}
        APP_NAME: ${{ secrets.APP_NAME }}
      run: docker build -t $APP_NAME:latest .

    - name: Push Docker Image to Container Registry GCR
      id: push-docker-image
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        IMAGE_TAG: ${{ github.sha }}
      run: |- 
        docker tag $APP_NAME:latest gcr.io/devops-labs-397603/services/nginx-example/prod:latest
        docker tag $APP_NAME:latest gcr.io/devops-labs-397603/services/nginx-example/prod:$IMAGE_TAG
        docker push gcr.io/devops-labs-397603/services/nginx-example/prod:latest
        docker push gcr.io/devops-labs-397603/services/nginx-example/prod:$IMAGE_TAG
