name: Deploy APP - GCP
on: 
  push:
    branches: ["dev"]
  workflow_dispatch:
   
env:
  APP_NAME:  ${{ secrets.APP_NAME }}
  INSTANCE_TAG:  "nginx-prod"
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  ZONE: "southamerica-east1-a"
  INSTANCE_NAME: "nginx-sample"
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      id: checkout
      uses: actions/checkout@v2
    
    - name: Login to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        
    - name: Configure Docker Client
      id: configure-docker-client
      run:  |-
        gcloud auth configure-docker southamerica-east1-docker.pkg.dev
    
    - name: Set Version
      id: version
      run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      id: build-docker-image
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID}}
        APP_NAME: ${{ secrets.APP_NAME }}
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
       
        INSTANCE_NAMES=$(gcloud compute instances list --filter="tags.items=$INSTANCE_TAG" --format="value(name)")
        
        # Execute the docker run command on each instance
        for INSTANCE_NAME in $INSTANCE_NAMES; do
          echo "Deploying to $INSTANCE_NAME"
          gcloud compute ssh $INSTANCE_NAME --zone $ZONE --command "
            sudo docker run -d -p 80:80 nginx
          "
        done
