name: Deploy APP
on: 
  workflow_dispatch:
  push:
    branches: ["master"]

env:
  DOCKER_TAG: latest
  GCP_REGION: ${{ secrets.GCP_REGION }}}
  GCR_REGISTRY: ${{ secrets.GCR_REGISTRY}}
  APP_NAME:  ${{ secrets.APP_NAME }}
  INSTANCE_TAG:  ${{ secrets.INSTANCE_TAG }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      id: checkout
      uses: actions/checkout@v2
    
    - name: Login to GCR
      id: login-gcr
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true
        
    - name: Configure Docker Client
      id: configure-docker-client
      run:  |-
        gcloud auth configure-docker southamerica-east1-docker.pkg.dev
    
    - name: Set Version
      id: version
      run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      id: build-docker-image
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID}}
        APP_NAME: ${{ secrets.APP_NAME }}
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        DOCKER_IMAGE="southamerica-east1-docker.pkg.dev/$PROJECT_ID/$APP_NAME:$VERSION"
        gcloud auth configure-docker southamerica-east1-docker.pkg.dev
        docker build -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE 
